export default {
    URLS: {
        FINDCREDITAUDITRECORDS: 'Apartment/Api/v1/FindCreditAuditRecords',
        FINDAPARTMENTREPORT: 'Apartment/Api/v1/FindApartmentReport',
        FINDCREDITREPORTBATCHCONTENT: 'CreditReport/Api/v1/FindCreditReportBatchContent',
        UPDATECREDITAUDIT: 'Apartment/Api/v1/UpdateCreditAudit'
    },
    KCURLS: {
        // overview 
        GETOVERVIEWMONTHLYSTATISTICS: 'api/Apartment/GetOverviewMonthlyStatistics?dateStr=',
        GETOVERVIEWDAYSTATISTICS: 'api/Apartment/GetOverviewDayStatistics?dateStr=',
        GETOVERVIEWCOMMONSTATISTICS: 'api/Apartment/GetOverviewCommonStatistics',
        // contract
        CONTRACTCREATE: 'api/Contract/Create',
        GETCONTRACTS: 'api/Contract/QueryContracts',
        REFRESHCONTRACTS: 'api/Contract/RefreshContracts',
        GETAPARTMENTS: 'api/Apartment/GetApartments',
        CREATEAPARTMENT: 'api/Apartment/CreateApartment',
        CREATEROOM: 'api/Room/CreateRoom',
        CREATEFLOORS: "api/Apartment/CreateFloors",
        DELETEFLOOR: 'api/Apartment/DeleteFloor',
        UPDATEROOM: 'api/Room/UpdateRoom',
        CREATEROOMRESERVATION: "api/RoomReservation/CreateRoomReservation",
        CANCELROOMRESERVATIONSTATE: 'api/RoomReservation/CancelRoomReservationState',
        REVOKEROOMRESERVATION: 'api/RoomReservation/RevokeRoomReservation',
        GETROOM: "api/Room/GetRoom?roomId=",
        DELETEROOM: 'api/Room/DeleteRoom',
        GETROOMSFROMCACHE: "api/Room/GetRoomsFromCache?apartmentId=",
        REFRESHROOMINFOS: 'api/Room/RefreshRoomInfos?apartmentId=',
        GETSTATISTICSDATA: 'api/Apartment/GetStatisticsData?apartmentId=',
        GETROOMINFOSTATISTICS: 'api/Apartment/GetRoomInfoStatistics',
        GETAPARTMENTROOMRENTSTATUS: "api/Apartment/GetApartmentRoomRentStatus?apartmentId=",
        REFRESHAPARTMENTROOMRENTSTATUS: "api/Apartment/RefreshApartmentRoomRentStatus?apartmentId=",
        GETCONTRACTBYROOMID: 'api/Contract/GetContractByRoomId?roomId=',
        GETCONTRACTBYCONTRACTID: 'api/Contract/GetContract?contractId=',
        GETPOSTLOANMANAGEMENTSBYCONTRACTID: 'api/PostLoanManagement/GetPostLoanManagementsByContractId?contractId=',
        CREATEPOSTLOANMANAGEMENT: 'api/PostLoanManagement/CreatePostLoanManagement',
        GETORDERSBYCONTRACTID: 'api/Order/GetOrdersByContractId?contractId=',
        GETINSTALLMENTORDERSANDNORMALORDERS: 'api/InstallmentOrder/GetInstallmentOrdersAndNormalOrders?contractId=',
        GETORDERBYORDERID: "api/Order/GetOrderByOrderId?orderId=",
        GETTENANTBYCELLPHONE: 'api/Tenant/GetTenantByCellphone?cellphone=',

        GETLOANDETAILS: 'api/Loan/GetLoanDetails',
        QUERYLOANINFOS: 'api/Loan/QueryLoanInfos',
        REFRESHLOANINFOS:"api/Loan/RefreshLoanInfos",

        GETLOANCAPITALORDERS: 'api/CapitalOrder/GetLoanCapitalOrders',
        QUERYCAPITALORDERINFOS: 'api/CapitalOrder/QueryCapitalOrderInfos',
        REFRESHCAPITALORDERINFOS:"api/CapitalOrder/RefreshCapitalOrderInfos",
        GETTRANSACTIONSBYORDERID: 'api/Transaction/GetTransactionsByOrderId?orderId=',
        //
        SENDCAPTCHA: "api/Sms/Tenancy/SendCaptcha",
        VERIFYCAPTCHA: "api/Sms/Tenancy/VerifyCaptcha",
        SIGNUP: "api/Account/SignUp",
        SIGNINBYPASSWORD: "api/Account/SignInByPassword",
        SIGNINBYSMSCODE: "api/Account/SignInBySmsCode",
        CHANGEPASSWORD: "api/Account/ChangePassword",
        GETROOMRESERVATIONSBYROOMID: 'api/RoomReservation/GetRoomReservationsByRoomId?roomId=',
        QUERYRESERVATIONS: "api/RoomReservation/QueryReservationInfos",
        REFRESHRESERVATIONINFOS: "api/RoomReservation/RefreshReservationInfos",
        UPDATEROOMRESERVATIONINFO: "api/RoomReservation/UpdateRoomReservationInfo",
        QUERYORDERS: "api/Order/QueryOrders",
        QUERYORDERINFOS: "api/Order/QueryOrderInfos",
        REFRESHORDERINFOS: "api/Order/RefreshOrderInfos",
        // Organization
        QUERYCITIES: 'api/Organization/QueryCities',
        QUERYDISTRICTS: 'api/Organization/QueryDistricts',
        CREATEDISCTRICT: 'api/Organization/CreateDisctrict',
        DELETEDISTRICT: 'api/Organization/DeleteDistrict',
        DELETEDISTRICT: 'api/Organization/DeleteDistrict',
        QUERYDEPARTMENTS: 'api/Organization/QueryDepartments',
        CREATEDEPARTMENT: 'api/Organization/CreateDepartment',
        DELETEDEPARTMENT: 'api/Organization/DeleteDepartment',
        QUERYPOSITIONS: 'api/Organization/QueryPositions',
        CREATEPOSITION: 'api/Organization/CreatePosition',
        DELETEPOSITION: 'api/Organization/DeletePosition',
        ORDERCREATE: "api/Order/Create",
        UPDATEORDER: 'api/Order/UpdateOrder',
        QUERYROOMBYROOMNUMBER: "api/Room/QueryRoomByRoomNumber",
        GETNORMALORDERBYORDERID: "api/Order/QueryOrderInfoByOrderId?orderId=",
        QUERYORDERBYORDERID: "api/Order/QueryOrderByOrderId",
        QUERYINSTALLMENTORDERINFO: "api/InstallmentOrder/QueryInstallmentOrderInfo?installmentOrderId=",
        //
        CREATETRANSACTION: "api/Transaction/CreateTransaction",
        UPDATETRANSACTIONANONYMOUS: "api/Transaction/UpdateTransactionAnonymous",
        QUERYTRANSACTIONINFOS:"api/Transaction/QueryTransactionInfos",
        REFRESHRANSACTIONINFOS:"api/Transaction/RefreshransactionInfos",
        CHECKOUTFIRSTSTEP:"api/Contract/CheckoutFirstStep?contractId=",
        CHECKOUTSECONDSTEP:"api/Contract/CheckoutSecondStep?contractId=",
        BATCHCREATE:"api/Order/BatchCreate",
        DELETEORDER:"api/Order/DeleteOrder",
        QUERYALLORDERSBYCONTRACTID:"api/Contract/QueryAllOrdersByContractId?contractId=",
        PAIDALLORDERS:"/api/Contract/PaidAllOrders",
        CHECKOUT:"api/Contract/Checkout",

        GETLOANAPPLIES: "api/Loan/GetLoanApplies",
        GETLOANAPPLYSTATISTICS: "api/Loan/GetLoanApplyStatistics",
        GETLOANFINANCIALSTATISTICS: "api/Loan/GetLoanFinancialStatistics",

        QUERYUTILITIESEXPENSES: 'api/UtilitiesExpense/QueryUtilitiesExpenses',
        REFRESHUTILITIESEXPENSES: 'api/UtilitiesExpense/RefreshUtilitiesExpenses',
        GETLASTUTILITIESEXPENSE: 'api/UtilitiesExpense/GetLastUtilitiesExpense?contractId=',
        CREATEUTILITIESEXPENSE: 'api/UtilitiesExpense/CreateUtilitiesExpense',
        DELETEUTILITIESEXPENSE: 'api/UtilitiesExpense/DeleteUtilitiesExpense',
        UPDATEUTILITIESEXPENSE: 'api/UtilitiesExpense/UpdateUtilitiesExpense'
    },
    REGEXS: {
        AMOUNT: /^\d{1,9}(\.\d{1,2})?$/,
        TEL: /^1[34578]\d{9}$/,
        IDCARD: /^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X)$/,
        LICENSENO: /^[京津沪渝冀豫云辽黑湘皖鲁新苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼使领A-Z]{1}[A-Z]{1}[A-Z0-9]{4}[A-Z0-9挂学警港澳]{1}$/,
        CHECKCODE: /^\d{6}$/,
        PASSWORD: /^[a-zA-Z\d~!@#$%^&*_]{6,18}$/
    },
    MSGINFO: {},
    COOKIES: {
        XKCSID: 'X-KC-SID',
        XKCAPIKEY: 'X-KC-APIKEY'
    }
};
